In [77]:
from pathlib import Path
import pandas as pd
import numpy as np

In [78]:
Path.cwd()

WindowsPath('C:/Users/oliver.horner/Code/thunderbird_psd/active_notebooks')

In [79]:
neutron_data_path = Path.cwd().parents[2] / "Documents" / "Neutron Data"
neutron_data_path

WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data')

In [80]:
unconverted_data_path = neutron_data_path / "1-Unconverted_Data"
converted_data_path = neutron_data_path / "2-Converted_Data"

### CSV files (straight from Compass)

In [81]:
exp_data_path = unconverted_data_path / "ID-289" / "UNFILTERED"

In [82]:
csv_file_paths = [x for x in exp_data_path.iterdir() if x.suffix.lower() == '.csv']

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\oliver.horner\\Documents\\Neutron Data\\1-Unconverted_Data\\ID-289\\UNFILTERED'

In [ ]:
with open(csv_file_paths[0], 'r') as openfile:
    headers_line = openfile.readline()
    data_sample_line = openfile.readline()

col_names = headers_line.strip().split(';')[:-1]
cols_count = len(data_sample_line.strip().split(';'))
samples_count = cols_count - len(col_names)
samples_col_names = [str(i) for i in range(samples_count)]
col_names += samples_col_names

In [ ]:
dfs = []
total_rows = 0
for i, csv_path in enumerate(csv_file_paths):
    header = 0 if i == 0 else None
    df = pd.read_csv(csv_path, sep=';', header=0, names=col_names)
    rows = df.shape[0]
    print(rows)
    dfs.append(df)
    total_rows += rows

In [83]:
total_rows

806774

In [84]:
full_df = pd.concat(dfs).sort_values("TIMETAG", ignore_index=True)
csv_rows = full_df.shape[0]
csv_rows

806774

In [85]:
full_df.dropna().shape[0]

806774

### Old Converter Parquet Files

In [86]:
# exp_data_path = converted_data_path/'testing'/'ID-289-original'/'processed_data'/'unfiltered'/'psd'
# parquet_file_paths = [x for x in exp_data_path.iterdir() if x.suffix.lower() == '.parquet']
# parquet_file_paths

In [87]:
# dfs = []
# total_rows = 0
# for i, parquet_path in enumerate(parquet_file_paths):
#     header = 0 if i == 0 else None
#     df = pd.read_parquet(parquet_path)
#     rows = df.shape[0]
#     print(rows)
#     dfs.append(df)
#     total_rows += rows

In [88]:
# total_rows

In [89]:
# full_df_old = pd.concat(dfs)
# old_rows = full_df_old.shape[0]
# old_rows

In [90]:
# full_df_old.dropna().shape[0]

In [91]:
# full_df_old = pd.read_parquet(parquet_file_paths)
# full_df_old.shape[0]

In [58]:
# full_df_old.dropna().shape[0]

### New Converter Parquet Files

In [59]:
exp_data_path = converted_data_path/'ID-289'/'processed_data'/'unfiltered'/'psd'
parquet_file_paths = [x for x in exp_data_path.iterdir() if x.suffix.lower() == '.parquet']
parquet_file_paths

[WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_0.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_1.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_10.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_11.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_12.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_13.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_14.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_15.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_16.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_17.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_18.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_19.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_2.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_20.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_21.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_22.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_23.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_24.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_25.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_26.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_27.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_28.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_29.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_3.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_4.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_5.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_6.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_7.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_8.parquet'),
 WindowsPath('C:/Users/oliver.horner/Documents/Neutron Data/2-Converted_Data/ID-289/processed_data/unfiltered/psd/caen_psd__SData_ID-289_9.parquet')]

In [60]:
dfs = []
total_rows = 0
for i, parquet_path in enumerate(parquet_file_paths):
    header = 0 if i == 0 else None
    df = pd.read_parquet(parquet_path)
    rows = df.shape[0]
    print(rows)
    dfs.append(df)
    total_rows += rows

26962
26951
26929
26929
26951
26929
26929
26929
26930
26929
26929
26929
26929
26929
26929
25717
26951
26941
26929
26929
26930
26929
26929
26929
26929
26930
26929
26930
26929
26930

In [61]:
total_rows

806774

In [62]:
full_df_new = pd.concat(dfs).sort_values("TIMETAG", ignore_index=True)
new_rows = full_df_new.shape[0]
new_rows

806774

In [63]:
full_df_new.dropna().shape[0]

806774

In [64]:
full_df_new = pd.read_parquet(parquet_file_paths)
full_df_new.shape[0]

806774

In [65]:
full_df_new.dropna().shape[0]

806774

### What's missing?

In [66]:
csv_rows - new_rows

-29

In [67]:
csv_rows

806745

In [68]:
new_rows

806774

In [69]:
full_df.head()

,BOARD,CHANNEL,TIMETAG,ENERGY,CALIB_ENERGY,ENERGYSHORT,FLAGS,PROBE_CODE,0,1,...,190,191,192,193,194,195,196,197,198,199
0,0,0,12423928436,1753,1.229990,1528,0x4000,1,14743,14743,...,14754,14754,14757,14757,14755,14755,14755,14755,14756,14756
1,0,0,20681320326,619,0.435690,523,0x4000,1,14746,14746,...,14748,14748,14753,14753,14706,14706,14746,14746,14748,14748
2,0,0,27562898403,184,0.131681,175,0x4000,1,14753,14753,...,14751,14751,14750,14750,14751,14751,14750,14750,14750,14750
3,0,0,36256833041,1091,0.765987,952,0x4000,1,14755,14755,...,14749,14749,14746,14746,14747,14747,14748,14748,14745,14745
4,0,0,36285771211,2616,1.836200,2299,0x4000,1,14748,14748,...,14737,14737,14749,14749,14749,14749,14746,14746,14757,14757

In [70]:
full_df_new.head()

,BOARD,CHANNEL,TIMETAG,ENERGY,CALIB_ENERGY,ENERGYSHORT,FLAGS,PROBE_CODE
0,0,0,12423928436,1753,1.22999,1528,0x4000,1
1,0,0,20681320326,619,0.43569,523,0x4000,1
2,0,0,27562898403,184,0.131681,175,0x4000,1
3,0,0,36256833041,1091,0.765987,952,0x4000,1
4,0,0,36285771211,2616,1.8362,2299,0x4000,1

In [71]:
timetag_csv = full_df["TIMETAG"].sort_values(ignore_index=True)
print(timetag_csv.shape)
timetag_csv_prev = timetag_csv.shift().fillna(-1).astype("int64")
print(timetag_csv.head())
print(timetag_csv_prev.head())
timetag_ascending = timetag_csv <= timetag_csv_prev
timetag_ascending[timetag_ascending].index

(806745,)
0    12423928436
1    20681320326
2    27562898403
3    36256833041
4    36285771211
Name: TIMETAG, dtype: int64
0             -1
1    12423928436
2    20681320326
3    27562898403
4    36256833041
Name: TIMETAG, dtype: int64

Int64Index([], dtype='int64')

In [72]:
timetag_new = full_df_new["TIMETAG"].astype("int64").sort_values(ignore_index=True)
print(timetag_new.shape)
timetag_new_prev = timetag_new.shift().fillna(-1).astype("int64")
print(timetag_new.head())
print(timetag_new_prev.head())
timetag_ascending_new = timetag_new <= timetag_new_prev
print(timetag_ascending_new.shape)
bad_indices = timetag_ascending_new[timetag_ascending_new].index
print(bad_indices)
print(timetag_new[bad_indices])

(806774,)
0    12423928436
1    20681320326
2    27562898403
3    36256833041
4    36285771211
Name: TIMETAG, dtype: int64
0             -1
1    12423928436
2    20681320326
3    27562898403
4    36256833041
Name: TIMETAG, dtype: int64
(806774,)
Int64Index([], dtype='int64')
Series([], Name: TIMETAG, dtype: int64)

In [73]:
added_timetag = np.setdiff1d(timetag_new.to_numpy(), timetag_csv.to_numpy())
print(added_timetag)
print(list(added_timetag))
full_df_new[full_df_new["TIMETAG"].astype("int64").isin(added_timetag)]

[ 222386312814723  443054631294780  660463464480353  879532065208652
 1097229582147865 1314059738134541 1527781908289853 1741107429177439
 1956546462349377 2172373605966160 2388106959693721 2603908112905638
 2819380420692727 3033890085282047 3248927877393928 3465848314293619
 3679856008759264 3892577782635119 4109452387241780 4324196821517336
 4538305720739775 4752874988754873 4967121400040907 5182780259108951
 5397245369802109 5614113835346995 5830480201184960 6046910288434651
 6260265763909412]
[222386312814723, 443054631294780, 660463464480353, 879532065208652, 1097229582147865, 1314059738134541, 1527781908289853, 1741107429177439, 1956546462349377, 2172373605966160, 2388106959693721, 2603908112905638, 2819380420692727, 3033890085282047, 3248927877393928, 3465848314293619, 3679856008759264, 3892577782635119, 4109452387241780, 4324196821517336, 4538305720739775, 4752874988754873, 4967121400040907, 5182780259108951, 5397245369802109, 5614113835346995, 5830480201184960, 6046910288434651, 6260265763909412]

,BOARD,CHANNEL,TIMETAG,ENERGY,CALIB_ENERGY,ENERGYSHORT,FLAGS,PROBE_CODE
26962,0,0,222386312814723,360,0.254637,303,0x4000,1
53913,0,0,3892577782635119,204,0.14565,183,0x4000,1
80842,0,0,4109452387241780,1229,0.86264,1084,0x4000,1
107771,0,0,443054631294780,95,0.0695277,79,0x4000,1
134722,0,0,4324196821517336,269,0.191055,225,0x4000,1
161651,0,0,4538305720739775,168,0.120506,146,0x4000,1
188580,0,0,4752874988754873,562,0.395833,377,0x4000,1
215509,0,0,4967121400040907,361,0.255336,309,0x4000,1
242439,0,0,5182780259108951,1067,0.749181,939,0x4000,1
269368,0,0,5397245369802109,267,0.189658,222,0x4000,1
296297,0,0,5614113835346995,222,0.158223,182,0x4000,1
323226,0,0,2172373605966160,468,0.330118,394,0x4000,1
350155,0,0,5830480201184960,256,0.181973,238,0x4000,1
377084,0,0,6046910288434651,182,0.130284,154,0x4000,1
404013,0,0,6260265763909412,360,0.254637,247,0x4000,1
429730,0,0,660463464480353,134,0.0967613,118,0x4000,1
456681,0,0,879532065208652,538,0.379053,473,0x4000,1
483622,0,0,1097229582147865,153,0.11003,134,0x4000,1
510551,0,0,1314059738134541,1387,0.973349,1204,0x4000,1
537480,0,0,1527781908289853,1027,0.721175,880,0x4000,1
564410,0,0,1741107429177439,2807,1.97056,2444,0x4000,1
591339,0,0,1956546462349377,182,0.130284,163,0x4000,1
618268,0,0,2388106959693721,271,0.192452,238,0x4000,1
645197,0,0,2603908112905638,682,0.479751,610,0x4000,1
672126,0,0,2819380420692727,682,0.479751,595,0x4000,1
699056,0,0,3033890085282047,1290,0.905376,1093,0x4000,1
725985,0,0,3248927877393928,2007,1.40826,1779,0x4000,1
752915,0,0,3465848314293619,602,0.423803,519,0x4000,1
779844,0,0,3679856008759264,2883,2.02405,2515,0x4000,1

In [74]:
full_df.iloc[[215703, 215704, 215705]]

,BOARD,CHANNEL,TIMETAG,ENERGY,CALIB_ENERGY,ENERGYSHORT,FLAGS,PROBE_CODE,0,1,...,190,191,192,193,194,195,196,197,198,199
215703,0,0,1742372627048809,249,0.177083,216,0x4000,1,14753,14753,...,14748,14748,14718,14718,14748,14748,14747,14747,14755,14755
215704,0,0,1742379068184432,126,0.091175,117,0x4000,1,14753,14753,...,14751,14751,14754,14754,14749,14749,14752,14752,14751,14751
215705,0,0,1742379503772277,772,0.542708,646,0x4000,1,14750,14750,...,14751,14751,14753,14753,14751,14751,14754,14754,14750,14750

In [75]:
full_df_new.iloc[[215703, 215704, 215705]]

,BOARD,CHANNEL,TIMETAG,ENERGY,CALIB_ENERGY,ENERGYSHORT,FLAGS,PROBE_CODE
215703,0,0,4968919035099074,562,0.395833,488,0x4000,1
215704,0,0,4968921742760550,593,0.417509,397,0x4000,1
215705,0,0,4968927753488055,1270,0.891364,1108,0x4000,1

In [76]:
# https://stackoverflow.com/questions/61691228/element-wise-comparison-of-two-pandas-dataframes

for col_name in list(full_df_new.columns):
    csv_series = full_df[col_name]
    csv_dtype = csv_series.dtype
    new_series = full_df_new[col_name].astype(csv_dtype)
    csv_array = csv_series.to_numpy()
    new_array = new_series.to_numpy()
    print(f"Series: {col_name}")
    
    print(np.equal(csv_array, new_array))

Series: BOARD

ValueError: operands could not be broadcast together with shapes (806745,) (806774,)